src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("snippets.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/snippets/urls.py
from django.urls import path

from .views import (
    SnippetCreateView,
    SnippetDeleteView,
    SnippetDetailView,
    SnippetUpdateView,
)

app_name = "snippets"
urlpatterns = [
    path("", SnippetCreateView.as_view(), name="index"),
    path("<str:url>/", SnippetDetailView.as_view(), name="snippet_detail"),
    path("<str:url>/edit/", SnippetUpdateView.as_view(), name="snippet_edit"),
    path("<str:url>/delete/", SnippetDeleteView.as_view(), name="snippet_delete"),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Main page{% endblock %} | Pastebox</title>
  <link rel="icon" href="{% static 'icons/box.svg' %}" type="image/svg+xml">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  {% block extra_head %}{% endblock %}
</head>
<body class="bg-secondary bg-opacity-10 d-flex flex-column min-vh-100">
<header>
  <nav class="navbar bg-warning bg-gradient border-bottom shadow-sm">
    <div class="container">
      <a class="navbar-brand fw-bold" href="{% url 'snippets:index' %}">
        PASTEBOX <img src="{% static 'icons/box.svg' %}" alt="logo" width="20">
      </a>
      {% if user.is_authenticated %}
        <div class="dropdown">
          <button class="btn btn-link text-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ user }}
          </button>
          <ul class="dropdown-menu dropdown-menu-end bg-light mt-2">
            <li>
              <a class="dropdown-item" href="{{ user.get_absolute_url }}">
                <img src="{% static 'icons/person.svg' %}" alt="profile" width="20">
                Profile
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'account_email' %}">
                <img src="{% static 'icons/email.svg' %}" alt="email" width="20">
                Change e-mail
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'account_change_password' %}">
                <img src="{% static 'icons/password.svg' %}" alt="password" width="20">
                Change password
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item text-danger" href="{% url 'account_logout' %}">
                <img src="{% static 'icons/logout.svg' %}" alt="logout" width="20">
                Log out
              </a>
            </li>
          </ul>
        </div>
      {% else %}
        <div class="d-flex">
          <a class="btn text-decoration-underline me-1" href="{% url 'account_login' %}">
            Log In
          </a>
          <a class="btn btn-success" href="{% url 'account_signup' %}">
            Sign Up
          </a>
        </div>
      {% endif %}
    </div>
  </nav>
</header>

<div class="container border border-top-0 bg-white py-3 shadow-sm">
  {% if messages %}
    <div class="row px-3">
      {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    </div>
  {% endif %}

  {% block content %}
  {% endblock %}
</div>

<div class="container my-4"></div>
<footer class="container-fluid bg-white mt-auto border-top shadow-sm">
  <p class="text-center fw-bold my-3">&copy; {% now 'Y' %} All rights reserved.</p>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>