src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("snippets.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/snippets/urls.py
from django.urls import path

from .views import (
    SnippetCreateView,
    SnippetDeleteView,
    SnippetDetailView,
    SnippetUpdateView,
)

app_name = "snippets"
urlpatterns = [
    path("", SnippetCreateView.as_view(), name="index"),
    path("<str:url>/", SnippetDetailView.as_view(), name="snippet_detail"),
    path("<str:url>/edit/", SnippetUpdateView.as_view(), name="snippet_edit"),
    path("<str:url>/delete/", SnippetDeleteView.as_view(), name="snippet_delete"),
]

src/snippets/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import QuerySet
from django.urls import reverse
from django.utils import timezone

from .utils import make_random_string

User = get_user_model()


class InactiveSnippetManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        """Return expired Snippets."""
        return super().get_queryset().filter(expiration__lte=timezone.now())


class ActiveSnippetManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        """Return unexpired Snippets."""
        return super().get_queryset().exclude(expiration__lte=timezone.now())


class Snippet(models.Model):
    """
    A model for storing any text or
    source code with syntax highlighting.
    """

    DEFAULT_TITLE = "Untitled"
    BODY_MAX_LENGTH = 65_536  # limited to 256 KiB (utf-8)
    URL_LENGTH = 8
    LANGUAGES = [
        # The value of the first element of the tuple must be
        # a short name from https://pygments.org/languages/
        ("", "None"),
        ("bash", "Bash"),
        ("c", "C"),
        ("cpp", "C++"),
        ("csharp", "C#"),
        ("css", "CSS"),
        ("go", "Go"),
        ("haskell", "Haskell"),
        ("html", "HTML"),
        ("java", "Java"),
        ("js", "JavaScript"),
        ("json", "JSON"),
        ("lua", "Lua"),
        ("md", "Markdown"),
        ("mysql", "MySQL"),
        ("objc", "Objective-C"),
        ("perl", "Perl"),
        ("php", "PHP"),
        ("postgres", "PostgreSQL"),
        ("python", "Python"),
        ("ruby", "Ruby"),
        ("rust", "Rust"),
        ("smalltalk", "Smalltalk"),
        ("sql", "SQL"),
        ("swift", "Swift"),
        ("toml", "TOML"),
        ("ts", "TypeScript"),
        ("yaml", "YAML"),
    ]

    author = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True, related_name="snippets"
    )
    title = models.CharField(max_length=100, blank=True, default=DEFAULT_TITLE)
    body = models.CharField(max_length=BODY_MAX_LENGTH)
    syntax = models.CharField(max_length=15, blank=True, choices=LANGUAGES)
    created_at = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField(null=True, blank=True)
    url = models.CharField(max_length=URL_LENGTH, unique=True, editable=False)

    # managers
    objects = models.Manager()
    inactive = InactiveSnippetManager()
    active = ActiveSnippetManager()

    class Meta:
        ordering = ("-created_at",)

    def __str__(self) -> str:
        """Return the snippet title shortened to 50 characters."""
        shorten_to = 50
        title = self.title
        if len(title) > shorten_to:
            title = title[:shorten_to]
            title = f"{title}..."
        return title

    def save(self, *args, **kwargs) -> None:
        self.title = self.title or self.DEFAULT_TITLE
        self.url = self.url or self._generate_unique_url()
        return super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        return reverse("snippets:snippet_detail", kwargs={"url": self.url})

    def _generate_unique_url(self) -> str:
        """Return a random URL string, which isn't in the database.

        Called recursively if the URL exists in the database.
        """
        url = make_random_string(self.URL_LENGTH)
        if Snippet.objects.filter(url=url).exists():
            return self._generate_unique_url()
        return url

src/snippets/forms.py
from datetime import timedelta

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Layout, Submit

from django import forms
from django.urls import reverse
from django.utils import timezone

from .models import Snippet


class SnippetForm(forms.ModelForm):
    TIME_LIMITS = [
        ("", "Never"),
        ("10", "10 Minutes"),
        ("1H", "1 Hour"),
        ("1D", "1 Day"),
        ("1W", "1 Week"),
        ("1M", "1 Month"),
        ("6M", "6 Months"),
        ("1Y", "1 Year"),
    ]
    expiration = forms.ChoiceField(choices=TIME_LIMITS, required=False)

    class Meta:
        model = Snippet
        fields = ("title", "body", "syntax", "expiration")
        widgets = {"body": forms.Textarea(attrs={"rows": 25})}
        labels = {
            "body": False,
            "syntax": "Syntax highlighting",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["title"].initial = ""  # set html attr: value
        self.helper.form_method = "POST"
        self.helper.form_action = reverse("snippets:index")
        self.helper.form_class = "row"
        self.helper.layout = Layout(
            Div("body", css_class="col-8"),
            Div(
                Div(Div("title", css_class="col"), css_class="row"),
                Div(
                    Div("syntax", css_class="col"),
                    Div("expiration", css_class="col"),
                    css_class="row",
                ),
                Submit("create", "Create", css_class="btn btn-success"),
                css_class="col-4",
            ),
        )

    def clean_expiration(self) -> timezone.datetime | None:
        """Returns datetime object with time limit otherwise None.

        The time limit is defined in the TIME_LIMITS list
        by the first element of each tuple.
        """
        time_code = self.cleaned_data["expiration"]
        match time_code:
            case "10":
                time_limit = timedelta(minutes=10)
            case "1H":
                time_limit = timedelta(hours=1)
            case "1D":
                time_limit = timedelta(days=1)
            case "1W":
                time_limit = timedelta(weeks=1)
            case "1M":
                time_limit = timedelta(days=30)
            case "6M":
                time_limit = timedelta(days=183)
            case "1Y":
                time_limit = timedelta(days=366)
            case _:
                return None

        return timezone.now() + time_limit

src/snippets/views.py
from crispy_forms.layout import Submit

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView
from django.views.generic.edit import DeletionMixin

from .forms import SnippetForm
from .mixins import AuthorSnippetRequiredMixin
from .models import Snippet


class SnippetCreateView(CreateView):
    model = Snippet
    form_class = SnippetForm
    template_name = "snippets/index.html"

    def form_valid(self, form) -> HttpResponseRedirect:
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user
        return super().form_valid(form)


class SnippetDetailView(DetailView):
    queryset = Snippet.active.all()
    slug_field = "url"
    slug_url_kwarg = "url"
    context_object_name = "snippet"


class SnippetUpdateView(AuthorSnippetRequiredMixin, UpdateView):
    form_class = SnippetForm
    template_name = "snippets/snippet_edit.html"

    def get_form(self, form_class=None) -> SnippetForm:
        form = super().get_form(form_class)
        form.helper.form_action = reverse(
            "snippets:snippet_edit", kwargs={"url": self.object.url}
        )
        # change submit button
        form.helper.layout[1][2] = Submit("edit", "Edit", css_class="btn btn-warning")
        return form


class SnippetDeleteView(AuthorSnippetRequiredMixin, DeletionMixin, View):
    def get_success_url(self):
        return self.request.user.get_absolute_url()

src/snippets/templates/snippets/index.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <h1 class="fs-4">New paste</h1>
    {% crispy form %}
{% endblock %}

src/snippets/templates/snippets/snippet_detail.html
{% extends "base.html" %}
{% load static %}
{% load snippets_filters %}

{% if snippet.syntax %}
  {% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/syntax_highlight.css' %}">
  {% endblock %}
{% endif %}

{% block title %}{{ snippet.title|truncatechars:30 }}{% endblock %}

{% block content %}
  <h1 class="fs-3 text-break">{{ snippet.title|capfirst }}</h1>

  <div class="row">
    <div class="col">
      <p class="text-muted">
        {% if snippet.author %}
          <span class="me-2">
            <img src="{% static 'icons/person.svg' %}" alt="person" width="20">
            <a href="{{ snippet.author.get_absolute_url }}">{{ snippet.author.username }}</a>
          </span>
        {% endif %}
        <span class="me-2" title="Created at">
          <img src="{% static 'icons/calendar.svg' %}" alt="calendar" width="20">
          {{ snippet.created_at|date:'j M, Y' }}
        </span>
        <span title="Will be unavailable in">
          <img src="{% static 'icons/stopwatch.svg' %}" alt="watch" width="20">
          {% if snippet.expiration %}
            {{ snippet.expiration|timeuntil }}
          {% else %}
            Never
          {% endif %}
        </span>
      </p>
    </div>
    {% if user.is_authenticated %}
      <div class="col-auto pe-0">
        <a class="btn btn-warning btn-sm" href="{% url 'snippets:snippet_edit' snippet.url %}" role="button">
          Edit
        </a>
      </div>
      <div class="col-auto">
        <form action="{% url 'snippets:snippet_delete' snippet.url %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger btn-sm">
            Delete
          </button>
        </form>
      </div>
    {% endif %}
  </div>

  {% if snippet.syntax %}
    <div class="card mb-4">
      <div class="card-header bg-success p-2 bg-opacity-50">
        Syntax: <span class="fw-bold">{{ snippet.get_syntax_display }}</span>
      </div>
      <div class="card-body bg-light table-responsive">
        {{ snippet|highlight_code }}
      </div>
    </div>
  {% endif %}

  <div class="card">
    <div class="card-header bg-warning p-2 text-dark bg-opacity-50">
      Plain text
    </div>
    <div class="card-body bg-light">
      <pre>{{ snippet.body }}</pre>
    </div>
  </div>
{% endblock %}

src/snippets/templates/snippets/snippet_edit.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Edit: {{ snippet.title|truncatechars:30 }}{% endblock %}

{% block content %}
  <h1 class="fs-4">Editing the paste</h1>
  {% crispy form %}
{% endblock %}